apiVersion: v1
kind: Pod
metadata:
  name: nginx-automountserviceaccounttoken-disallowed
  labels:
    app: nginx-automountserviceaccounttoken
spec:
  automountServiceAccountToken: true
  containers:
  - name: nginx
    image: openpolicyagent/nginx
    resources:
      limits:
        cpu: "150m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "256Mi"
