apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: updated-system-aggregate-to-edit
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
  # Existing rules from the original file
  - apiGroups:
      - ""
    resources:
      - pods/attach
      - pods/exec
      - pods/portforward
      - pods/proxy
      - secrets
      - services/proxy
    verbs:
      - get
      - list
      - watch
  # Add any additional rules or modify existing rules as needed

