apiVersion: v1
kind: Pod
metadata:
  name: opa-alloweed
  labels:
    owner: me.agilebank.demo
spec:
  automountServiceAccountToken: false
  containers:
    - name: opa
      image: openpolicyagent/opa:0.9.2
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
      resources:
        limits:
          cpu: "200m"
          memory: "1Gi"
        requests:
          cpu: "100m"
          memory: "1Gi"



